Update/dem
LLNL/spheral pull request #215
Opened 2023-05-08 13:52 UTC by jmpearl

# Summary

- This is a significant overhaul of the DEM package
- It does the following:
  - new term "neighborSearchBuffer" controls fast time stepping se
  - neighbor search distance initialized in more robust manner from particle radius
  - particle's uniqueIndex handled robustly for on-the-fly generation
  - solid boundary conditions have been added
  - fieldlists offloaded from DEM phys package to nodelists

------
### ToDo :

- [ ] Annotate ``RELEASE_NOTES.md`` with notable changes.
- [ ] Create LLNLSpheral PR pointing at this branch. (PR#)
- [ ] LLNLSpheral PR has passed all tests.

2023-06-13 20:04 UTC, mdavis36 requested changes
Just a few empty files and some nitpicking but otherwise looks good 👍

2023-06-13 20:04 UTC, mdavis36 commented on src/DEM/SolidBoundary/DEMBoundaryPolicyInline.hh
remove?

2023-06-13 20:04 UTC, mdavis36 commented on src/DEM/SolidBoundary/SolidBoundaryBase.hh
> +
empty scope

2023-06-13 20:04 UTC, mdavis36 commented on src/DEM/SolidBoundary/SolidBoundaryBaseInline.hh
remove?

2023-06-14 23:33 UTC, jmpearl commented on src/DEM/SolidBoundary/SolidBoundaryBaseInline.hh
Thanks for catching these!

2023-06-16 14:54 UTC, mdavis36 approved these changes

2023-06-16 16:08 UTC, merged