Fix ENABLE_DEV_BUILD
LLNL/spheral pull request #306
Opened 2024-10-04 14:16 UTC by ldowen

# Summary

- This PR is fixes `ENABLE_DEV_BUILD`
- It does the following:
  - Removes any hacks that were in `ENABLE_DEV_BUILD` that prevented it from exporting or required special lists/logic
  - Changes one of the CI tests to use `ENABLE_DEV_BUILD` to ensure it will not break as often

------
### ToDo :

- [ ] Annotate ``RELEASE_NOTES.md`` with notable changes.
- [ ] Create LLNLSpheral PR pointing at this branch. (PR#)
- [ ] LLNLSpheral PR has passed all tests.

2024-10-04 22:10 UTC, jmikeowen submitted a review, later dismissed
Tested this out and it's working for me

2024-10-08 15:18 UTC, mdavis36 requested changes

2024-10-08 15:18 UTC, mdavis36 commented on .gitlab/specs.yml
> +    EXTRA_CMAKE_ARGS: '-DENABLE_DOCS=On -DENABLE_WARNINGS_AS_ERRORS=On -DENABLE_DEV_BUILD=On'
Could we move this to a different config, we build `gcc_mvapich2` as our release build so testing for the dev build with it isn't ideal. Maybe `clang_mavapich2`, or `gcc_spectrum`?

2024-10-08 16:18 UTC, mdavis36 approved these changes

2024-10-09 17:08 UTC, jmikeowen approved these changes

2024-10-15 16:00 UTC, merged